### ISSUE TITLE
在这个项目里，也没看见证书和私匙文件，不知你的wss是如何起作用的？

### ISSUE THREAD

**Issue by luckypoem** [net-byte/wsocks#1]
HI.
看了源码，没发现该项目自带的证书和私匙文件，不知你的wss是如何起作用的？虽然客户端的配置文件和服务器端的配置文件里都有写明‘ws.scheme=wss’。

**Comment by net-byte** [comment]
服务端用的是自签证书，如果想用其他证书，可以用nginx反响代理ws
SelfSignedCertificate ssc = new SelfSignedCertificate();
sslCtx = SslContextBuilder.forServer(ssc.certificate(), ssc.privateKey()).build();
